# spring properties
spring.application.name=NGP GUI
spring.main.allow-bean-definition-overriding=true
spring.main.show_banner=false
server.error.whitelabel.enabled=false
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html
spring.freemarker.check-template-location=false


# app configurations 
#app.pdir = C:/workspace/AISDEV/code/pdir/
app.pdir = C:/Users/FIS/Source/AML/Application/aml-gui-frontend/AML_Frontend/pdir/

logging.config=${app.pdir}/properties/logback.xml

app.multids.base-packages = com.ogi


# datasource configurations
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@10.75.84.30:6000:ORAAIS
#spring.datasource.username=FrontEnd
#spring.datasource.password=FrontEnd#1

DB_SCHEMA=amlschema
spring.datasource.url=jdbc:postgresql://aisworld.space:9000/fiuaml
spring.datasource.username=fiuaml
spring.datasource.password=FINaml@DO_GRES_25
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.jpa.properties.hibernate.jpa.query.group_by.interpretation=compatible
spring.datasource.hikari.connection-init-sql=SET search_path TO ${DB_SCHEMA};
spring.jpa.hibernate.ddl-auto=update



#entity managment
spring.jpa.properties.hibernate.integrator_provider=com.ogi.main.configurations.schemaConfigurations.CustomIntegratorProvider
spring.jpa.properties.hibernate.hbm2ddl.schema_filter_provider=com.ogi.main.configurations.schemaConfigurations.AnnotationBasedSchemaFilterProvider


spring.datasource.max-active=2
spring.datasource.max-idle=8
spring.datasource.min-idle=3
spring.datasource.initial-size=5
spring.datasource.validation-query=
spring.datasource.test-on-borrow=false
spring.datasource.test-on-return=false
spring.datasource.test-while-idle=false
spring.datasource.time-between-eviction-runs-millis=30000
spring.datasource.min-evictable-idle-time-millis=60000
spring.datasource.max-wait=10000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000


spring.devtools.restart.enabled=false

#logs 
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.springframework.security=DEBUG




plugins.directory=${app.pdir}/plugins/



#flyway configurations 

spring.flyway.enabled = true
spring.flyway.locations = filesystem:${app.pdir}/migrations
spring.flyway.baseline-on-migrate=true

file.path=C:/Users/FIS/Source/AML/Document/SampleFiles/

accessfile.path=C:/Users/FIS/Source/AML/Document/


hadoop.home.dir=C:/winutils
	

###Redis Config
spring.redis.host=aisworld.space
spring.redis.port=9200